### ISSUE TITLE
The error when compute_deviations 

### ISSUE THREAD

**Issue by houruiyan** [lzj1769/pychromVAR#11]
Dear Dr , 
I meet another problem, when I run pychromvar. 
The error looks like this. 
![image](https://user-images.githubusercontent.com/56068158/225553521-e6a1c028-53ab-47d9-bf56-a1b3b7f49d6d.png)
Can you help me? Thank you!

**Comment by houruiyan** [comment]
Even in the example data, it produce this error.

**Comment by lzj1769** [comment]
This seems to be an issue related to multiple CPUs.

You can try to set the number of CPUs as 1 by:
`pc.compute_deviations(mdata, n_jobs=1)`

Note that this may increase the running time .

**Comment by houruiyan** [comment]
Thank you for your reply! I wonder if I run demo file with n_jobs=1, how long does it spend?

**Comment by houruiyan** [comment]
Thank you very much. It works.
